name: Create Azure Resource Group

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  create-resource-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Azure
        uses: azure/login@v1
        with:
          id: ${{ secrets.AZURE_CLIENT_ID }}
          secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          scope: "subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      - name: Create Resource Group
        uses: azure/arm-deploy@v1
        with:
          scope: "subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          template: "./azure-resource-group.json"
          deploymentName: mydeployment
