name: Create Azure Resource Group

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch

jobs:
  create-resource-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Azure
        uses: azure/login@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          cred: ${{ secrets.AZURE_CREDENTIALS }}
          #tenantId: ${{ secrets.AZURE_TENANT_ID }}
          

      - name: Create Resource Group
        uses: azure/arm-deploy@v1
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: "./azure-resource-group.json"
          deploymentName: mydeployment
